### ISSUE TITLE
Is there a way to add find my phone feature?

### ISSUE THREAD

**Issue by MattL0** [PfisterDaniel/node-red-apple-find-me#1]
hi, thanks for this great package. 

I wonder, if thee is a way to use the find my phone to retrieve (ring) our ios device ?

thank you

**Comment by PfisterDaniel** [comment]
Hi,
i will check this.

**Comment by PfisterDaniel** [comment]
Hi,

i'm written a new Version, in this Version you can trigger the "Find my iPhone" - function and you can send messages to your devices. I close this Issue...

**Comment by MattL0** [comment]
Thanks a lot !!

Sent from an Iphone
________________________________

**Comment by MattL0** [comment]
Just tested . It works perfect. Thanks a lot.

**Comment by PfisterDaniel** [comment]
No Problem...
Thanks for testing.
Br Daniel

Am 11.11.2020 um 21:02 schrieb MattL0 <notifications@github.com>:

﻿

Just tested . It works perfect. Thanks a lot.
