### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by jspeckman** [PfisterDaniel/node-red-apple-find-me#2]
Would it be possible to add the ability to update the timer interval via input message?

Thanks!

**Comment by PfisterDaniel** [comment]
Is it... but it is not so nice. How interval is your favorite? I will add this to my Combobox.

**Comment by jspeckman** [comment]
I would like to be able to change the timer interval  to different values by sending a message to the node, rather than having a fixed timer interval set in the node.

**Comment by PfisterDaniel** [comment]
Ok, I'll check that out. It is currently the case that the UpdateInterval cannot be set variable during the runtime. It's a little more complicated.

**Comment by PfisterDaniel** [comment]
It's this a solution for you?

<img width="890" alt="ScreenShot" src="https://user-images.githubusercontent.com/9358627/99669588-92596280-2a6f-11eb-96ee-625359d01c59.png">

**Comment by jspeckman** [comment]
Yes, I believe that would work.

**Comment by PfisterDaniel** [comment]
Ok, it's coming with the new release

**Comment by PfisterDaniel** [comment]
New version 1.0.5 was published
